name: Push on `main`

on:
  push:
    branches: main

jobs:
  # python_docker_release:
  #   uses: openclimatefix/.github/.github/workflows/python-docker-release.yml@standalone-release
  #   with:
  #     image_base_name: ocf_github_workflow_test
  #   secrets:
  #     token: ${{ secrets.PYPI_API_TOKEN }}
  #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  #     DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  # python-release:
  #   uses: openclimatefix/.github/.github/workflows/python-release.yml@standalone-release
  #   secrets:
  #     token: ${{ secrets.PYPI_API_TOKEN }}
      
  docker-release:
    uses: openclimatefix/.github/.github/workflows/docker-release.yml@standalone-release
    with:
      image_base_name: ocf_github_workflow_test
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  #
  # New workflows not yet merged
  #
  # bump-version:
  #   uses: openclimatefix/.github/.github/workflows/bump-version.yml@standalone-release

  # docker-release:
  #   needs: bump-version
  #   uses: openclimatefix/.github/.github/workflows/docker-release-only.yml@standalone-release
  #   with:
  #     image_base_name: ocf_github_workflow_test
  #     tag_value: ${{ needs.bump-version.outputs.new_ver }}
  #     checkout_submodules: true

  #   secrets:
  #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  #     DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
